### ISSUE TITLE
settings on Poco phones

### ISSUE THREAD

**Issue by Vader77Darth** [R9TRH/MIUIwidgets#26]
When installing the module on a Poco phone, the "home screen" button in settings apps redirects to Poco launcher. This can be fixed by installing the Poco launcher add on module in the telegram which simply adds one system property. This extra module is unnecessary. The system property should just be in miui widgets module considering that every Poco phone needs it.

**Comment by R9TRH** [comment]
Hello. Please describe it more, and also note that I have not telegram, no longer :)

**Comment by R9TRH** [comment]
Also that Poco addon that u said, as I remember, adds a property that cannot be added by the MW module itself

**Comment by Vader77Darth** [comment]
Put a system.prop file in the module with the one line 
ro.miui.product.home=com.miui.home

**Comment by R9TRH** [comment]
> Put a system.prop file in the module with the one line ro.miui.product.home=com.miui.home

As I said, it connot be added by the Main module, I tried before

**Comment by Vader77Darth** [comment]
Oh.
