### ISSUE TITLE
Poco add-on is broken

### ISSUE THREAD

**Issue by Vader77Darth** [R9TRH/MIUIwidgets#28]
The new Poco Add-on doesn't have an install.sh and doesn't REPLACE="
/system/priv-app/MiLauncherGlobal
"
This breaks Poco launcher and miui launcher cannot be installed.

**Comment by R9TRH** [comment]
Hmm
Thanks for reporting👍
Will be fixed in next release

**Comment by Vader77Darth** [comment]
Thanks!
