### ISSUE TITLE
Maybe this can help for the future of MIUI 14 Support

### ISSUE THREAD

**Issue by joeyoropesa-dev** [R9TRH/MIUIwidgets#30]
(This is the non-tested-yet solution for the Themes modded app in MIUI 14 Global ROMs)

I find out that the MIUI Themes app for Global ROM are moved to the dir /product/app/MIUIThemeManagerGlobal/MIUIThemeManagerGlobal.apk and in that directory there is oat folder with oat files of that app so if the dev create Global ROM version of this module for MIUI 14 and generates oat folder with the content (arm64/MIUIThemeManagerGlobal.odex and arm64/MIUIThemeManagerGlobal.vdex) and rename the apk file to be MIUIThemeManagerGlobal.apk and put it into directory in the module /product/app/MIUIThemeManagerGlobal/ it can help us to have Themes app to work in MIUI 14 if the app is compatible with the A13 version.

**Comment by admin-elvistrujanovic** [comment]
Somehow, the module doesn't let me to write on /product so before I got somehow this to work, I can't test it.

**Comment by R9TRH** [comment]
I really do not know about those advanced android developing

**Comment by R9TRH** [comment]
Btw I will try to find how it works if I find free time
I am very very busy these days
Hope you understand

**Comment by admin-elvistrujanovic** [comment]
> Btw I will try to find how it works if I find free time
> I am very very busy these days
> Hope you understand

Thank you so much 🥰
